In [1]:
import numpy as np

# 1D ARRAY

In [2]:
array1 = np.array([4, 8, 10, 15, 17])
print(array1)

[ 4  8 10 15 17]


In [3]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [4]:
np.linspace(1, 10, 8)


array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [5]:
np.ones((4, 7), dtype = np.int16)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [6]:
np.zeros((4,5), dtype = np.int16)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [7]:
np.full((3, 4), 1.5)

array([[1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5]])

In [8]:
array1 = np.array([4, 8, 10, 15, 17])

In [9]:
array1.shape

(5,)

In [10]:
array1.dtype

dtype('int32')

In [11]:
array1.size

5

In [12]:
array1.ndim

1

# 2D ARRAY

In [13]:
array2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
print(array2)

[[1 2 3 4]
 [4 5 6 7]]


In [14]:
array2.shape

(2, 4)

In [15]:
array2.size

8

In [16]:
array2.ndim

2

In [17]:
array2.dtype

dtype('int32')

In [18]:
array2.ravel()


array([1, 2, 3, 4, 4, 5, 6, 7])

# ARRAY SLICING

In [19]:
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [20]:
a = arr1[2:6]
print(a)

[2 3 4 5]


In [21]:
b = arr1[1::2]
print(b)

[1 3 5 7 9]


In [22]:
c = arr1[::-1]
print(c)

[10  9  8  7  6  5  4  3  2  1  0]


In [23]:
a[3] = 15
print(a)

[ 2  3  4 15]


In [24]:
arr1

array([ 0,  1,  2,  3,  4, 15,  6,  7,  8,  9, 10])

In [25]:
arr2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [26]:
a = arr2[3:8].copy()
print(a)

[3 4 5 6 7]


In [27]:
a[2] = 16
print(a)

[ 3  4 16  6  7]


In [28]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# RESHAPING OF ARRAY

In [29]:
arr3 = np.array([3, 4, 6, 8, 1, 49, 43, 25, 17, 98, 11, 14])

In [30]:
arr3.reshape(3,4)

array([[ 3,  4,  6,  8],
       [ 1, 49, 43, 25],
       [17, 98, 11, 14]])

In [31]:
arr3.reshape(6,2)

array([[ 3,  4],
       [ 6,  8],
       [ 1, 49],
       [43, 25],
       [17, 98],
       [11, 14]])

In [32]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# CONCATINATION

#1D ARRAY

In [33]:
a1 = np.array([1, 3, 5, 7, 9])

In [34]:
a2 = np.array([2, 4, 6, 8, 10])

In [35]:
np.concatenate([a1, a2])


array([ 1,  3,  5,  7,  9,  2,  4,  6,  8, 10])

In [36]:
np.vstack([a1, a2])

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [37]:
np.hstack([a1, a2])

array([ 1,  3,  5,  7,  9,  2,  4,  6,  8, 10])

In [38]:
np.append(a1, a2)

array([ 1,  3,  5,  7,  9,  2,  4,  6,  8, 10])

#2D ARRAY

In [39]:
a3 = np.array([[2, 4, 3],[1, 6, 7]])

In [40]:
a4 = np.array([[3, 6, 4],[2, 7, 5]])

In [41]:
np.concatenate([a3, a4])

array([[2, 4, 3],
       [1, 6, 7],
       [3, 6, 4],
       [2, 7, 5]])

In [42]:
np.vstack([a3, a4])

array([[2, 4, 3],
       [1, 6, 7],
       [3, 6, 4],
       [2, 7, 5]])

In [43]:
np.hstack([a3, a4])

array([[2, 4, 3, 3, 6, 4],
       [1, 6, 7, 2, 7, 5]])

In [44]:
np.append(a3, a4)

array([2, 4, 3, 1, 6, 7, 3, 6, 4, 2, 7, 5])

In [45]:
np.vsplit(a3, [2])

[array([[2, 4, 3],
        [1, 6, 7]]),
 array([], shape=(0, 3), dtype=int32)]

In [46]:
np.hsplit(a4, [2])

[array([[3, 6],
        [2, 7]]),
 array([[4],
        [5]])]

# MATHEMATICAL OPERATIONS 

In [47]:
array2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [48]:
array2*array2

array([[ 1,  4,  9, 16],
       [16, 25, 36, 49]])

In [49]:
array2+array2

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14]])

In [50]:
array2**array2

array([[     1,      4,     27,    256],
       [   256,   3125,  46656, 823543]])

In [51]:
array2.sum(axis=0)

array([ 5,  7,  9, 11])

In [52]:
array2.sum(axis=1)

array([10, 22])

In [53]:
array2 = np.array([[1, 2, 3],[3, 4, 6]])
print(array2)      

[[1 2 3]
 [3 4 6]]


In [54]:
array3 = np.array([[7, 2, 2], [8, 3, 6]])
print(array3)

[[7 2 2]
 [8 3 6]]


In [55]:
np.dot(array2, array3.transpose())

array([[17, 32],
       [41, 72]])

In [56]:
np.cross(array2, array3)

array([[ -2,  19, -12],
       [  6,  30, -23]])

In [57]:
array = np.array([1, 1, 2, 5, 6, 17, 19, 1, 3, 3, 6, 6, 19, 10, 19, 10])

In [58]:
array

array([ 1,  1,  2,  5,  6, 17, 19,  1,  3,  3,  6,  6, 19, 10, 19, 10])

In [59]:
np.argsort(array)

array([ 0,  1,  7,  2,  8,  9,  3,  4, 10, 11, 13, 15,  5,  6, 12, 14],
      dtype=int64)

In [60]:
np.argmin(array)

0

In [61]:
np.argmax(array)

6